[babel]

[beautifulsoup4]

[bottle]

[click]

[django]

[docspec]

[docutils]

[flask]

[httpx]

[jinja2]

[lxml]

[mako]

[markdown]

[mistletoe]
docformat = "google"

# Fails because of https://github.com/twisted/pydoctor/issues/501
# [numpy]

[pydoctor]
docformat = "epytext"

[pygments]

[requests]

[scrapy]

[setuptools]

[sphinx]

[sqlalchemy]

[werkzeug]
