[babel]
sphinx_inventory_url = "https://babel.pocoo.org/en/stable/objects.inv"

[beautifulsoup4]

[bottle]

[click]

[django]

[docutils]

[flask]

[httpx]

[jinja2]

[lxml]

[mako]

[markdown]

[mistletoe]

[numpy]

[pydoctor]
docformat = "epytext"

[pygments]

[requests]

[scrapy]

[setuptools]

[sphinx]
sphinx_inventory_url = "https://www.sphinx-doc.org/objects.inv"
# TODO: this is the inventory for the master branch, stable would be better

[sqlalchemy]

[werkzeug]
