[astroid]

[astor]

[babel]

[beautifulsoup4]

[bottle]

[click]

[django]

[docspec]

[docutils]

[dropbox]

[flask]

[httpx]

[jira]

[jinja2]

[klein]

[ldaptor]

[lxml]

[mako]

[markdown]

[mistletoe]
docformat = "google"

[mypy]

# Fails because of https://github.com/twisted/pydoctor/issues/501
# [numpy]

[pydoctor]
docformat = "epytext"

[pygments]

[python-dateutil]

[requests]

[scrapy]

[setuptools]

[sphinx]

[sqlalchemy]

[treq]

[twisted]

[urllib3]

[werkzeug]
