[astroid]

[astor]

[babel]

[beautifulsoup4]

[bottle]

[click]

[django]

[docspec]

[docutils]

[dropbox]

[flask]

[httpx]

[jira]

[jinja2]

[klein]
pydoctor_args = ["--docformat=epytext", ]

[ldaptor]

[lxml]

[mako]

[markdown]

[mistletoe]
pydoctor_args = ["--docformat=google", ]

[mypy]

[numpy]
pydoctor_args = ["--docformat=numpy", ]

[pydoctor]
pydoctor_args = ["--docformat=epytext", ]

[pygments]

[python-dateutil]

[requests]

[scrapy]

[setuptools]

[sphinx]

[sqlalchemy]

[treq]

[twisted]
pydoctor_args = ["--docformat=epytext", ]

[urllib3]

[werkzeug]
