[babel]
sphinx_inventory_url = "https://babel.pocoo.org/en/stable/objects.inv"

[beautifulsoup4]
sphinx_inventory_url = "https://www.crummy.com/software/BeautifulSoup/bs4/doc/objects.inv"

[bottle]
sphinx_inventory_url = "https://bottlepy.org/docs/stable/objects.inv"

[click]
sphinx_inventory_url = "https://click.palletsprojects.com/en/8.0.x/objects.inv"

[django]
sphinx_inventory_url = "https://docs.djangoproject.com/en/4.0/objects.inv"

[docutils]

[flask]
sphinx_inventory_url = "https://flask.palletsprojects.com/en/2.0.x/objects.inv"

[httpx]

[jinja2]
sphinx_inventory_url = "https://jinja.palletsprojects.com/en/3.0.x/objects.inv"

[lxml]

[mako]
sphinx_inventory_url = "https://docs.makotemplates.org/en/latest/objects.inv"

# [markdown]
# uses mkdocs -> we cannot reliably determine public / private API

[mistletoe]

[numpy]

[pydoctor]
docformat = "epytext"

[pygments]

[requests]

[scrapy]

[setuptools]

[sphinx]
sphinx_inventory_url = "https://www.sphinx-doc.org/objects.inv"
# TODO: this is the inventory for the master branch, stable would be better

[sqlalchemy]

[werkzeug]
