[astroid]

[astor]

[attrs]

[babel]

[beautifulsoup4]

[bottle]

[codetools]

[click]

[docker]

[django]

[djangorestframework]

[docspec]

[docutils]

[dropbox]

[fabric]

[flask]

[httpx]

[inspect4py]

[invoke]

[jira]

[jinja2]

[klara]

[klein]
pydoctor_args = ["--docformat=epytext", ]

[ldaptor]

[lunr]

[lxml]

[mako]

[markdown]

[mistletoe]
pydoctor_args = ["--docformat=google", ]

[mypy]

[numpy]
pydoctor_args = ["--docformat=numpy", ]

[py2cfg]

[pydoctor]
pydoctor_args = ["--docformat=epytext", ]

[pygments]

[pylint]

[python-dateutil]

[pytype]

[requests]

[scrapy]

#[selenium]

[setuptools]

[sphinx]

[sqlalchemy]

[toml]

[treq]

[twisted]
pydoctor_args = ["--docformat=epytext", ]

[urllib3]

[werkzeug]
