name: signals
on: 
  push:
    branches: 
      - main

jobs:
  run_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Send signal to build docs
        run: |
          
          curl -XPOST -u "${{secrets.GH_USERNAME}}:${{secrets.GH_TOKEN}}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/pydocbrowser/pydocbrowser.github.io/actions/workflows/build.yaml/dispatches \
            --data '{"ref": "master"}'
